config/routes.rb
Todo::Application.routes.draw do
  authenticated :user do
		root :to => 'lists#index'
	end

	root :to => "home#index"

	devise_for :users

	resources :users, :only => [:show, :index] do
    resources :lists do
      resources :tasks, :except => [:index, :show] do
        match "complete" => "tasks#complete", :via => :get
      end 
    end
  end

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, :dependent => :delete_all

  attr_accessible :title, :description, :completion_score

  validates :title, :presence => true

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  after_save :update_list_completion

  scope :completed, where(:done => true).order('due_date IS NULL, due_date ASC')
  scope :uncompleted, where(:done => false).order('due_date IS NULL, due_date ASC')

  attr_accessible  :title, :description, :due_date, :done

  validates_presence_of :title
  validates :due_date, :future_date => true, :on => :create


  private

  # Updates parent list completion score
  def update_list_completion
  	list_tasks = self.list.tasks
    number_tasks = list_tasks.size
    completed_tasks = list_tasks.completed.size
    self.list.update_attributes(:completion_score => ((completed_tasks.to_f/number_tasks.to_f) * 100).to_i )
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false

  def overdue_tasks
    @tasks = Task.where("done = false AND due_date < ?", Date.today)
      .joins(:list)
      .where(:lists => {:user_id => self})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 	def index
		@users = User.all
	end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @lists = current_user.lists
  end

  def new
    @list = List.new
  end

  def create
    @list = current_user.lists.create( params[:list] )
    if @list.save
      redirect_to user_lists_path( current_user ), :notice => t('lists.controller.create.success')
    else
      flash[:error] = t('lists.controller.create.failure')
      render :action => :new
    end
  end

  def show
    begin
      @list = current_user.lists.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to user_lists_path(current_user), :error => t('lists.controller.not_found') 
    end
    @completed_tasks = @list.tasks.completed
    @uncompleted_tasks = @list.tasks.uncompleted
  end

  def edit
    begin
      @list = current_user.lists.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to user_lists_path(current_user), :error => t('lists.controller.not_found') 
    end
  end

  def update
    begin
      @list = current_user.lists.find(params[:id])
    rescue ActiveRecord::RecordNotFound 
      redirect_to user_lists_path(current_user), :error => t('lists.controller.not_found') 
    end
    if @list.update_attributes(params[:list])
      redirect_to user_lists_path(current_user), :notice => t('lists.controller.update.success') 
    else
      flash[:error] = t('lists.controller.update.failure') 
      render :action => 'edit'
    end
  end

  def destroy
    begin
      @list = current_user.lists.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to user_lists_path( current_user ), :error => t('lists.controller.destroy.failure') 
    end
    @list.destroy
    redirect_to user_lists_path( current_user ), :notice => t('lists.controller.destroy.success')
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!

  def new
    @task = Task.new
  end

  def create
    @list = current_user.lists.find( params[:list_id] )
    @task = @list.tasks.create ( params[:task] )
    if @task.save
      redirect_to user_list_path( current_user, params[:list_id] ), :notice => t('tasks.controller.create.success')
    else
      flash[:error] = t('tasks.controller.create.failure')
      render :action => :new
    end
  end

  def edit
    begin
      list = current_user.lists.find(params[:list_id])
      @task = list.tasks.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to user_list_path(current_user, list), :error => t('lists.controller.not_found') 
    end
  end

  def update
    begin
      list = current_user.lists.find(params[:list_id])
      @task = list.tasks.find(params[:id])
    rescue ActiveRecord::RecordNotFound 
      redirect_to user_list_path(current_user, list), :error => t('tasks.controller.not_found') 
    end
    if @task.update_attributes(params[:task])
      redirect_to user_list_path(current_user, list), :notice => t('tasks.controller.update.success') 
    else
      flash[:error] = t('tasks.controller.update.failure') 
      render :action => 'edit'
    end
  end

  def complete
    begin
      list = current_user.lists.find(params[:list_id])
      @task = list.tasks.find(params[:task_id])
    rescue ActiveRecord::RecordNotFound 
      redirect_to user_list_path(current_user, list), :error => t('tasks.controller.not_found') 
    end
    if @task.update_attributes(:done => !@task.done)
      message = t('tasks.controller.change.do')
      unless @task.done
        message = t('tasks.controller.change.undo')
      end
      redirect_to user_list_path(current_user, list), :notice => message
    else
      redirect_to user_list_path(current_user, list), :error => t('tasks.controller.change.failure') 
    end
  end

  def destroy
    begin
      list = current_user.lists.find(params[:list_id])
      @task = list.tasks.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to user_list_path( current_user, params[:list_id] ), :error => t('tasks.controller.destroy.failure') 
    end
    @task.destroy
    redirect_to user_list_path( current_user, params[:list_id] ), :notice => t('tasks.controller.destroy.success')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/list_helper.rb
module ListHelper
  def print_overdue_tasks_badge
  	@number_overdue_tasks = current_user.overdue_tasks.size
    if @number_overdue_tasks != 0
      raw('<span class="badge badge-important">') +  pluralize(@number_overdue_tasks, t('lists.general.overdue_task')) + raw('</span>')
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="hero-unit">
  <h1><%= t('pages.home.title')%></h1>
  <p><%= t('pages.home.subtitle')%></p>
  <p><%= link_to t('pages.home.sign_up'), new_user_registration_path, :class => "btn btn-primary btn-large" %></p>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_signed_in_navigation.html.erb
<nav class="navbar-inner">
  <div class="container">
    <%= link_to t('pages.navigation.brand'), user_lists_path(current_user), :class => 'brand' %>
    <ul class="nav">
      <li><%= link_to raw('<i class="icon-tasks icon-white"></i> ') + t('pages.navigation.my_lists'), user_lists_path(current_user) %></li>
    </ul>
    <ul class="nav pull-right">
      <% overdue_tasks = current_user.overdue_tasks %>
      <% unless overdue_tasks.empty? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= print_overdue_tasks_badge %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% if overdue_tasks.size %>
              <% overdue_tasks.each do |overdue| %>
                <li><%= link_to overdue.title, user_list_path(current_user, overdue.list_id) %></li>
              <% end %>
            <% end %>
          </ul>
        </li>
      <% end %>
      <li class="divider-vertical"></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= raw '<i class="icon-user icon-white"></i>' %> Hi, <%= current_user.name %>! <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to t('edit_account'), edit_user_registration_path %></li>
          <li class="divider"></li>
          <li><%= link_to raw('<i class="icon-off"></i> ') + t('logout'), destroy_user_session_path, :method=>'delete' %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Thanx ToDo" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <% if user_signed_in? %>
        <%= render 'layouts/signed_in_navigation' %>
      <% else %>
        <%= render 'layouts/signed_out_navigation' %>
      <% end %>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
          <%= render 'layouts/messages' %>
          <%= yield %>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/lists/edit.html.erb
<%= simple_form_for @list, :url => user_list_path(current_user, @list), :html => {:class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.button :submit, :class => 'btn btn-primary' %> 
  <%= link_to t('cancel'), user_lists_path(current_user) , :class => "btn" %>
<% end %>

app/views/lists/index.html.erb
<% @lists.each do |list| %>
  <div class="row-fluid well">
  	<div class="span12">
      <div class="row-fluid">
        <div class="span9">
          <h3><%= link_to list.title, user_list_path(current_user, list) %></h3>
          <p><%= list.description %></p>
        </div>
        <div class="span3">
          <%  
            progres_bar_class = "info"
            if list.completion_score == 100
              progres_bar_class = "success"
            end
          %>
          <div class="progress progress-<%= progres_bar_class %> progress-striped">
            <div class="bar" style="width: <%= list.completion_score %>%"></div>
          </div>
          <div class="list_task_overview">
            <%= pluralize(list.tasks.size, t('lists.general.task')) %> - <%= list.tasks.completed.size %> <%= t('lists.general.completed') %>
          </div>
        </div> 
      </div>
    </div>
    <div class="span12">
      <%= link_to raw("<i class='icon-edit'></i> ") + t('edit'), edit_user_list_path(current_user, list), :class => "btn" %>
      <%= link_to raw("<i class='icon-trash icon-white'></i> ") + t('delete'), user_list_path(current_user, list), :class => "btn btn-danger", :method => :delete, :confirm => t('lists.views.index.delete_confirmation') %>
    </div>
  </div>
<% end %>
<h1><%= t("lists.views.index.no_records") if @lists.empty? %></h1>
<p><%= link_to raw("<i class='icon-plus icon-white'></i> ") + t("lists.views.new"), new_user_list_path(current_user), :class => "btn btn-primary" %></p>

app/views/lists/new.html.erb
<h1><%= t("lists.views.new") %></h1>
<%= simple_form_for @list, :url => user_lists_path(current_user), :html => {:class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.button :submit, :class => 'btn btn-primary' %> 
  <%= link_to t('cancel'), user_lists_path(current_user) , :class => "btn" %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>
<p><%= @list.description %></p>
<div class="well">
  <h2><%= t('tasks.general.tasks') %></h2>
  <% unless @uncompleted_tasks.empty? && @completed_tasks.empty? %>
    <table class="table">
      <thead>
    	  <th class="span1"></th>
    	  <th class="span2"><%= t('tasks.views.title') %></th>
    	  <th class="span4"><%= t('tasks.views.description') %></th>
    	  <th class="span3"><%= t('tasks.views.due_date') %></th>
    	  <th class="span2"></th>
    	</thead>
    	<tbody>
          <%= render :partial => 'tasks/uncompleted_task', :as => :task, :collection => @uncompleted_tasks %>
          <%= render :partial => 'tasks/completed_task', :as => :task, :collection => @completed_tasks %>
      </tbody>
    </table>
  <% else %>
    <%= t('tasks.views.no_tasks') %>
  <% end %>
</div>

<%= link_to raw("<i class='icon-plus icon-white'></i> New Task"), new_user_list_task_path(current_user, @list), :class => "btn btn-primary" %>

app/views/tasks/_completed_task.html.erb
<tr style="color:gray">
  <td>
    <%= link_to image_tag("checkbox_checked.png"), user_list_task_complete_path(current_user, @list, task) %>
  </td>
  <td><%= task.title %></td>
  <td <%= "data-toggle='modal' data-target='#task_#{task.id}' " if task.description.size > 100 %>>
    <%= truncate(task.description, :length => 100, :omission => '...') %>
    <div class="modal" id="task_<%= task.id %>" tabindex="-1" role="dialog" style="display:none; color:#333">
      <div class="modal-header">
        <h3><%= task.title %></h3>
      </div>
      <div class="modal-body">
        <p><%= task.description %></p>
      </div>
    </div>
  </td>
  <td>
    <%= task.due_date.strftime("%b %d, %Y") unless task.due_date.nil? %>
  </td>
  <td></td>
</tr>

app/views/tasks/_uncompleted_task.html.erb
<%
  overdue = false
  if !task.due_date.nil? && task.due_date < Date.today
    overdue = true
  end
%>
<tr <%= "class='error'" if overdue %>>
  <td>
    <%= link_to image_tag("checkbox_unchecked.png"), user_list_task_complete_path(current_user, @list, task) %>
  </td>
  <td><%= task.title %></td>
  <td <%= "class='truncated' data-toggle='modal' data-target='#task_#{task.id}' " if task.description.size > 100 %>>
    <%= truncate(task.description, :length => 100, :omission => '...') %>
    <div class="modal" id="task_<%= task.id %>" tabindex="-1" role="dialog" style="display:none">
      <div class="modal-header">
        <h3><%= task.title %></h3>
      </div>
      <div class="modal-body">
        <p><%= task.description %></p>
      </div>
    </div>
  </td>
  <td>
  	<% unless task.due_date.nil? %>
      <%= task.due_date.strftime("%b %d, %Y") %>
	    <%= " - " + pluralize((Date.today - task.due_date).to_i, t('tasks.views.day')) + " " + t('tasks.views.overdue') if overdue %>
	<% end %>
  </td>
  <td>
    <%= link_to raw("<i class='icon-edit'></i> ") + t('edit'), edit_user_list_task_path(current_user, @list, task), :class => "btn btn-small" %>
    <%= link_to raw("<i class='icon-trash icon-white'></i> ") + t('delete'), user_list_task_path(current_user, @list, task), :class => "btn btn-danger btn-small", :method => :delete, :confirm => t('tasks.views.delete_confirmation') %>
  </td>
</tr>

app/views/tasks/edit.html.erb
<%= simple_form_for @task, :url => user_list_task_path(current_user, params[:list_id], @task), :html => {:class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :due_date, :wrapper => :append do %>
    <%= f.input_field :due_date, :as => :date_picker %><span class="add-on"><i class="icon-calendar"></i></span>
  <% end %>
  <%= f.button :submit, :class => 'btn btn-primary'%> 
  <%= link_to t('cancel'), user_list_path(current_user, params[:list_id]) , :class => "btn" %>
<% end %>

app/views/tasks/new.html.erb
<%= simple_form_for @task, :url => user_list_tasks_path(current_user, params[:list_id]), :html => {:class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :due_date, :wrapper => :append do %>
    <%= f.input_field :due_date, :as => :date_picker %><span class="add-on"><i class="icon-calendar"></i></span>
  <% end %>
  <%= f.button :submit, :class => 'btn btn-primary' %> 
  <%= link_to t('cancel'), user_list_path(current_user, params[:list_id]) , :class => "btn" %>
<% end %>